### ISSUE TITLE
SIGSEGV in data_channel_set_item

### ISSUE THREAD

**Issue by ptrcnull** [rumpeltux/brother-scand#4]
gdb log:
```
$ gdb --args ./build/brother-scan-cli -d -c out/brother.config
Reading symbols from ./build/brother-scan-cli...
(gdb) r
Starting program: /home/patrycja/Downloads/brother-scand/build/brother-scan-cli -d -c out/brother.config

Program received signal SIGSEGV, Segmentation fault.
memcpy () at src/string/x86_64/memcpy.s:18
18	src/string/x86_64/memcpy.s: No such file or directory.
(gdb) bt full
#0  memcpy () at src/string/x86_64/memcpy.s:18
No locals.
#1  0x000055555555d2d4 in data_channel_set_item (data_channel=0x7fffffffe160, 
    item=0x0) at data_channel.c:796
No locals.
#2  0x0000555555556796 in main (argc=4, argv=0x7fffffffe318) at scanner_cli.c:59
        option = -1
        config_path = 0x7fffffffe702 "out/brother.config"
        data_channel = {conn = 0x0, process_cb = 0x0, tempfile = 0x0, 
          scan_id = 0, page_data = {id = 0, remaining_chunk_bytes = 0}, 
          scanned_pages = 0, thread = 0x0, params = {{id = 0 '\000', 
              value = '\000' <repeats 15 times>} <repeats 16 times>}, xdpi = 0, 
          ydpi = 0, width = 0, height = 0, config = 0x7ffff7ffefb0, item = 0x0, 
          file_format = 0x0}
```

**Comment by rumpeltux** [comment]
Thanks for the report. Does this consistently reproduce?

**Comment by ptrcnull** [comment]
it does. it might be just something missing from my config, as i added the bare minimum to the example config

**Comment by DestyNova** [comment]
I ran into this same issue. After some embarrassing printf-debugging, it's segfaulting for me because my config file contains no `preset ... ...` line. I'm not sure why it used to work before. If no preset was found, it tries to read the TAILQ of `data_channel.config->items` and gets back a null pointer, which then gets passed to `memcpy` and blows up.
